defaults:
  - base
  - _self_

name: word_definitions
datasets: ["word_instances", "word_types", "word_synonyms",
 "word_types_synthetic", "word_instances_synthetic", "word_synonyms_synthetic"]

datasets_test: []
agg: full