from abc import ABC, abstractmethod


class BaseProbeRunner(ABC):
    def __init__(self, cfg): ...
    def single_training(self, X, y, mask): ...
    def parameter_search(self, X, y, mask): ...
    def conformal_training(self, X_cal, y_cal): ...
    def decision_function(self, X): ...
    @property
    def direction(self): ...
    @property
    def bias(self): ...
