defaults:
  - base_llama
  - _self_

name: _llama-3.1-8b-bio
model: ContactDoctor/Bio-Medical-Llama-3-8B
token: INSERT_ACCESS_TOKEN
layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
instruct: True