defaults:
  - base_probe

name: mean_diff
with_bags: False # If false then uses only the last token in the sentence

init_params:
  with_covariance: True
  verbose: True
  fit_intercept: True
param_grid: 
  with_covariance: [True, False]
  fit_intercept: [True, False]