defaults:
  - base_probe

# Mean-difference classifier(Single Instance Probe)
name: mean_diff
with_bags: False # If false then uses only the last token in the sentence

train_sample_limit: 1000000 # Limit the number of training samples (aka bags) for trainings

init_params:
  with_covariance: True
  verbose: False
  cov_type: "oas"
  cov_reg: 1e-8
  tol: 1e-8
  fit_intercept: True
param_grid: 
  cov_type: ["empirical"] # on search it is better to use empirical covariance (faster)
  with_covariance: [True, False]
  fit_intercept: [True, False]