defaults:
  - base_probe

# Supervised PCA probe (Single Instance Probe)
name: spca
with_bags: False
train_sample_limit: 1000000 # Limit the number of training samples (aka bags) for trainings


init_params:
  n_components: 1000
  cov_type: "oas" #"oas"
  verbose: True
param_grid:
  n_components:  [1, 10, 100, 500, 1000, 1500, 2000] 
  cov_type: ["empirical"] # on search it is better to use empirical covariance (faster)


