defaults:
  - base_probe

name: svm
with_bags: False

init_params:
  multi_class: 'ovr'
  penalty: 'l2'
  loss: 'hinge'
  fit_intercept: True
  dual: 'auto'
  C: 1.0
  class_weight: 'balanced'
  max_iter: 5000
param_grid: 
  C: [0.05, 0.1, 0.5, 1, 10]