defaults:
  - base_probe

name: svm
train_bag_limit: 1800
with_bags: False # this probes works only with the last token in the sentence
init_params:
  kernel: linear
  penalty: -1
  C: 0.1
  scale_C: True
  verbose: True
  sv_cutoff: 1e-7
param_grid:
  C: [0.05, 0.1, 0.5, 1, 10]