defaults:
  - base_probe

# Training Truth and Polarity Directions (Single Instance Probe)
name: ttpd
with_bags: False
train_sample_limit: 1000000 # Limit the number of training samples (aka bags) for trainings

init_params:
  random_seed: 42
  verbose: True
param_grid:
  random_seed: [42]

  ## check if polarity is correctly assigned