# @package _global_
hydra:
  job_logging:
    version: 1
    disable_existing_loggers: false
    root:
      level: WARNING  # Suppress all logs below WARNING globally
    loggers:
      sklearn.utils.validation:
        level: WARNING  # Suppress INFO logs for sklearn.utils.validation
      sklearnex:
        level: WARNING  # Suppress INFO logs for sklearnex
  run:
    dir: outputs/hydra_logs/probes/${probe.name}/${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model: llama-3-8b
  - probe: sbMIL2
  - datapack: cities_loc
  - datapack@datapack_test: cities_loc
  - _self_

conformal_params:
  alpha: 0.1
  tie_breaking: False # Break ties based on p-val (True) or abstains (False)
  nc: 'binary'

eval_params:
  n_bootstraps: 1000
  max_bag_size: 100

task: 4
layer_range: [0.1, 1.0]
layer_id: None
search: True
agg: full
run_debugging: False

layers: ${model.layers}
variation: ""
trial_name: ${datapack.name}
output_dir: "outputs/probes/${probe.name}/${model.name}/"


random_seed: 42
batch_size: 12
limit_batches: -1 #number of batches to run the analysis on
sparsify_data: -1
cv_n_folds: 3
cv_bag_limit: 600
save_results: True
start_from_checkpoint: True # "last_finished" will start from the layer that was last computed (aka checkpointed)

