from __future__ import annotations

from abc import ABC, abstractmethod
from zipfile import Path

import numpy as np


class BaseProbeRunner(ABC):
    def __init__(self, cfg): ...
    def single_training(self, X, y, mask, *args): ...
    def parameter_search(self, X, y, mask, *args): ...
    def conformal_training(self, X_cal, y_cal): ...
    def conformal_prediction(self, X): ...
    @abstractmethod
    def decision_function(self, X): ...
    def predict_proba(self, X):
        """Needs to be rewritten for probes that return probabilities"""
        return self.decision_function(X)

    def predict(self, X):
        """Needs to be rewriten for probes that return probabilities"""
        scores = self.decision_function(X)
        return np.array(scores > 0)

    @property
    def direction(self): ...
    @property
    def bias(self): ...
    @property
    def estimator(self): ...
    @abstractmethod
    def bag_decision_function(self, X): ...
    @abstractmethod
    def bag_predict_proba(self, X): ...
    @abstractmethod
    def bag_predict(self, X): ...
    @abstractmethod
    def bag_conformal_prediction(self, X): ...
    @abstractmethod
    def inst_decision_function(self, X): ...
    @abstractmethod
    def inst_predict_proba(self, X): ...
    @abstractmethod
    def inst_predict(self, X): ...
    @abstractmethod
    def inst_conformal_prediction(self, X): ...
    @abstractmethod
    def load(self, output_dir: str | Path, layer_id: int): ...
